backup:
  root: /mnt/storage/Backup

  categories:
    macmini: MacMini
    ubuntu: Ubuntu
    windows: Windows
    databases: Databases
    compose: compose
    configs: configs
    docker_data: docker-data
    postgres: postgres
    logs: logs
    server_backup: server-backup
